# Generated by Django 5.0 on 2024-01-08 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vendorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
